export const TITELS = {
  petName: "Pet Name",
  animalType: "Animal Type",
  age: "Age",
  gender: "Gender",
  lastVaccinationDate: "Last Vaccination Date",
  lastVetVisit: "Last Vet Visit",
  medications: "Medications",
  allergies: "Allergies",
  name: "Name",
  phoneNumber: "Phone Number",
  about: "About",
  location: "Location",
  specialization: "Specialization",
};
